version: 2
jobs:
  build_with_exact_packages:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: npm run build
  build_with_compatible_packages:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
  test_build_with_node_6:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
  test_source_with_node_6:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_source
      - test_build:
          requires:
            - build
